// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk03xauVf4LgHCet9hJTIMm2FNWC6PFKg',
    appId: '1:514189556692:ios:d17bf41e51fc42106c3441',
    messagingSenderId: '514189556692',
    projectId: 'exeat-management-system',
    storageBucket: 'exeat-management-system.firebasestorage.app',
    iosBundleId: 'com.example.exeatSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk03xauVf4LgHCet9hJTIMm2FNWC6PFKg',
    appId: '1:514189556692:ios:d17bf41e51fc42106c3441',
    messagingSenderId: '514189556692',
    projectId: 'exeat-management-system',
    storageBucket: 'exeat-management-system.firebasestorage.app',
    iosBundleId: 'com.example.exeatSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaMPqp6sq8gKXJcIFNddHrNMHA9MkgBas',
    appId: '1:514189556692:web:7968aa065ebbe7b36c3441',
    messagingSenderId: '514189556692',
    projectId: 'exeat-management-system',
    authDomain: 'exeat-management-system.firebaseapp.com',
    storageBucket: 'exeat-management-system.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaMPqp6sq8gKXJcIFNddHrNMHA9MkgBas',
    appId: '1:514189556692:web:7968aa065ebbe7b36c3441',
    messagingSenderId: '514189556692',
    projectId: 'exeat-management-system',
    authDomain: 'exeat-management-system.firebaseapp.com',
    storageBucket: 'exeat-management-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0bscs1VF-_EaNHo2gY3QVAH7Cv3N53Dk',
    appId: '1:514189556692:android:101374906fb187d96c3441',
    messagingSenderId: '514189556692',
    projectId: 'exeat-management-system',
    storageBucket: 'exeat-management-system.firebasestorage.app',
  );

}